Conteúdo da View adicionar.phtml

<br />
<br />

<?php 

if (isset($this->view->objetos) && 	is_array($this->view->objetos)) { ?>

	<table class="table table-striped table-hover">
		<tr>
			<td><strong>ID</b></strong></td>
			<td><strong>Descrição</strong></td>
		</tr>
		<?php
			foreach($this->view->objetos as $k => $r) { ?>
				<tr>
					<td><?php echo $r['id']; ?></td>
					<td><?php echo $r['descricao']; ?></td>
				</tr>
			<?php } 
		?>
	</table>	
	<?php
} else {
	echo 'Não há registros';
}