<html lang="pt-BR">
	<head>
         <meta charset="utf-8">    
         <meta name="author" content="Leandro dos Reis Oliveira" />
         <meta name="language" content="pt-br" />
         <meta name="Copyright" content="Copyright (c) " />
         <meta name="description" content="" />
         <meta name="keywords" content="" />
         <script type="text/javascript" src="/_plugins/jquery/jquery.js"></script>
         <script type="text/javascript" src="/_plugins/bootstrap/js/bootstrap.min.js"></script>
         <link href="/_plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		 <link rel="stylesheet" href="/_css/estrutura.css" type="text/css" media="screen" />
		 <title>Micro framework - teste</title>
	</head>
	<body>
      	<div id="tudo">
      		﻿<div id="topo">
				<div class="container"> <br />Aqui fica o conteúdo do topo</div>
      		</div>
      		<div id="conteudo">
				<?php echo $this->content(); ?>
			</div>	
	    </div>	

		<div id="rodape" class="background-rodape">
	        <div class="container">
	            <div class="row text-center">
	                <br />
	                <br />
	                <br />
	                <br />
	                Aqui fica o conteúdo do rodapé
	            </div>
	        </div>
		</div>
	</body>
</html>
